#!/bin/sh

# Git pre-commit compile hook. Make project and in case of error abort commit.
# Script based on: http://benjamin-meyer.blogspot.com/2008/10/git-hooks.html
# Make sure this script is executable and set the Makefile location MAKEFILE.

# This file is part of a set of unofficial pre-commit hooks available
# at github.
# Link:    https://github.com/githubbrowser/Pre-commit-hooks
# Contact: David Martin, david.martin.mailbox@googlemail.com


###########################################################
# SETTINGS:
# Path to your makefile
# MAKEFILE="/home/user/project/src/Makefile"
MAKEFILE="/home/user/project/src/Makefile"

# Additional options for the make call. Eg. --quiet to not print any output
# or -j to make use of multiple cpu cores.
# OPTIONS="--quiet -j"
OPTIONS="--quiet"
###########################################################
# There should be no need to change anything below this line.

source $(dirname "$0")/"canonicalizeFilename.sh"

# exit on error
set -e

MAKEPATH="$(dirname "$MAKEFILE")"

echo "Building project."
if [ -f "$MAKEFILE" ] ; then
    cd "$MAKEPATH"
    make $OPTIONS -f "$MAKEFILE"
    if [ $? != 0 ] ; then
        echo "Build failure. Aborting commit."
        exit 1
    fi
    echo "Build success."
else
    echo "Error: Makefile not found. Aborting commit."
    echo "Set the correct path in $(canonicalizeFilename "$0")."
    echo "Skip pre-commit hooks with --no-verify (not recommended)."
    exit 1
fi

exit 0
