#!/bin/sh

# Git pre-commit compile hook. Make project and in case of error abort commit.
# Script based on: http://benjamin-meyer.blogspot.com/2008/10/git-hooks.html
# Make sure this script is executable and set the Makefile location MAKEFILE.

# Path to your makefile, eg. "/home/user/project/src/Makefile"
MAKEFILE="/home/user/project/src/Makefile"
MAKEPATH=$(dirname $MAKEFILE)

echo "Building project."
if [ -f $MAKEFILE ] ; then
    cd $MAKEPATH
    make -j --quiet -f $MAKEFILE
    if [ $? != 0 ] ; then
        echo "Build failure. Aborting commit.";
        exit 1
    fi
    echo "Build success."
else
    echo "Error: Makefile not found. Aborting commit."
    echo "Set the correct path in $(readlink -f $0)."
    echo "Skip pre-commit hooks with --no-verify (not recommended)."
    exit 1
fi

exit 0
